### PR TITLE
Various upgrades

### PR DESCRIPTION
**Pull request by MatMaul**
- fix newer versions with websocket by setting PUBLIC_URL
- add dynamic jvb nodeport support as in upstream jitsi-deployment
- add TCP support to JVB
- tweak network buffers size for JVB
- allow easy customization
- support ALB as an ingress

Missing are some update to the doc, but I feel that it is at least good enough for a review.

### CODE REVIEW

**Comment by krakazyabra** [comment]
Awsome job! thanks!
btw, did you test it on latest version of jitsi?

**Comment by MatMaul** [comment]
yes, it was tested with 5963 which is the last stable. The version is now hardcoded by default in `values.yml` to avoid breaking on upgrade, but can be tweaked by the user.

**Comment by krakazyabra** [comment]
Great. I'll update README to describe new values.

**Comment by MatMaul** [comment]
Thanks, yeah I think the main stuff missing before I am fully happy is updating the docs with the new values so if you can do it perfect !

**Pull request merged**
